# Site settings
title: CIS352
baseurl: "/cis352-s22" #"cis352"
url: "https://kmicinski.com"
description: "CMSC352--Principles of Programming Languages (Spring '22) at Syracuse"
permalink: pretty

# Build settings
#markdown: redcarpet

# Build posts to appear in the future
future: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
